### ISSUE TITLE
Create PR from Metacell/PsyneuLinkView to PrincetonUniversity/PsyNeuLinkView

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/PsyNeuLinkView#19]
Create a PR from the main branch of our repository https://github.com/MetaCell/PsyNeuLinkView

To their repository https://github.com/PrincetonUniversity/PsyNeuLinkView

**Comment by zsinnema** [comment]
@jrmartin we have 2 options here (since this repo is not a fork of https://github.com/PrincetonUniversity/PsyNeuLinkView)
1. change this repo to become a fork, a bit more complecated than 2
2. I can fork https://github.com/PrincetonUniversity/PsyNeuLinkView to my accounts, push the changes from here to my fork and from that fork create a PR

I prefer option 1 because this is the prefered way on GitHub

steps for option 1:
* rename the current repo so something different
* fork https://github.com/PrincetonUniversity/PsyNeuLinkView to metacell
* push from the renamed repo to the metacell fork
* copy all issues from the renamed repo to the forked metacell repo
* remove the renamed repo
* create a pr from the metacell fork

Unfortunately I don't have priviliges to do this.

**Comment by jrmartin** [comment]
We are going with option 1. We need @gidili to do the first step (rename) and second step (fork). @zsinnema picks up after second step.

1. rename the current repo so something different
2. fork https://github.com/PrincetonUniversity/PsyNeuLinkView to metacell
3. push from the renamed repo to the metacell fork
4. copy all issues from the renamed repo to the forked metacell repo
5. remove the renamed repo
6. create a pr from the metacell fork
